apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chart:
    name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 3.3.0
  values:
    controller:
      config:
        hsts: "false"
      daemonset:
        useHostPort: "true"
      hostNetwork: "true"
      kind: DaemonSet
      metrics:
        enabled: "true"
      podAnnotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      service:
        type: NodePort
